// frontend-admin/src/views/SettingsView.vue
<script setup lang="ts">
import { ref } from 'vue'

const settings = ref({
  appName: 'NexusLab',
  appUrl: 'http://localhost',
  email: 'admin@nexuslab.com',
  currency: 'COP',
  timezone: 'America/Bogota',
  maintenanceMode: false,
  advisorMonetization: false,
})

function saveSettings() {
  console.log('Saving settings:', settings.value)
}
</script>

<template>
  <div class="space-y-6">
    <div class="flex items-center justify-between">
      <div>
        <h1 class="text-2xl font-bold text-primary">Configuración</h1>
        <p class="text-text-secondary">Configuración general de la plataforma</p>
      </div>
      <button @click="saveSettings" class="btn-primary">Guardar cambios</button>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <!-- Main Settings -->
      <div class="lg:col-span-2 space-y-6">
        <div class="card">
          <h2 class="text-lg font-semibold text-primary mb-6">General</h2>
          <div class="space-y-4">
            <div>
              <label class="block text-sm font-medium text-primary mb-2">Nombre de la aplicación</label>
              <input v-model="settings.appName" type="text" class="input-field" />
            </div>
            <div>
              <label class="block text-sm font-medium text-primary mb-2">URL de la aplicación</label>
              <input v-model="settings.appUrl" type="text" class="input-field" />
            </div>
            <div>
              <label class="block text-sm font-medium text-primary mb-2">Email de contacto</label>
              <input v-model="settings.email" type="email" class="input-field" />
            </div>
          </div>
        </div>

        <div class="card">
          <h2 class="text-lg font-semibold text-primary mb-6">Localización</h2>
          <div class="grid grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-primary mb-2">Moneda</label>
              <select v-model="settings.currency" class="input-field">
                <option value="COP">Peso Colombiano (COP)</option>
                <option value="USD">Dólar (USD)</option>
                <option value="EUR">Euro (EUR)</option>
              </select>
            </div>
            <div>
              <label class="block text-sm font-medium text-primary mb-2">Zona horaria</label>
              <select v-model="settings.timezone" class="input-field">
                <option value="America/Bogota">Bogotá (UTC-5)</option>
                <option value="America/Mexico_City">Ciudad de México (UTC-6)</option>
                <option value="America/Buenos_Aires">Buenos Aires (UTC-3)</option>
              </select>
            </div>
          </div>
        </div>
      </div>

      <!-- Sidebar Settings -->
      <div class="space-y-6">
        <div class="card">
          <h2 class="text-lg font-semibold text-primary mb-6">Sistema</h2>
          <div class="space-y-4">
            <label class="flex items-center justify-between cursor-pointer">
              <span class="text-sm text-primary">Modo mantenimiento</span>
              <input v-model="settings.maintenanceMode" type="checkbox" class="rounded text-accent" />
            </label>
            <div class="pt-4 border-t border-gray-100">
              <p class="text-xs text-text-secondary">
                Cuando está activado, solo los administradores pueden acceder al sitio.
              </p>
            </div>
          </div>
        </div>

        <div class="card">
          <h2 class="text-lg font-semibold text-primary mb-6">Monetización</h2>
          <div class="space-y-4">
            <label class="flex items-center justify-between cursor-pointer">
              <span class="text-sm text-primary">Cobrar por conexión de asesores</span>
              <input v-model="settings.advisorMonetization" type="checkbox" class="rounded text-accent" />
            </label>
            <div class="pt-4 border-t border-gray-100">
              <p class="text-xs text-text-secondary">
                Si está desactivado, los asesores pueden conectar con tiendas gratis.
              </p>
            </div>
          </div>
        </div>

        <div class="card bg-accent/10 border-accent/20">
          <h3 class="font-semibold text-primary mb-2">Zona de peligro</h3>
          <p class="text-xs text-text-secondary mb-4">
            Estas acciones son irreversibles. Procede con precaución.
          </p>
          <button class="w-full py-2 px-4 bg-red-600 hover:bg-red-700 text-white rounded-xl text-sm font-medium transition-colors">
            Reiniciar plataforma
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

// frontend-client/src/pages/admin/SettingsView.jsx
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Settings as SettingsIcon, Mail, Shield, Bell, Globe, DollarSign, AlertTriangle, ImageIcon, ArrowRight } from 'lucide-react';
import { useSiteStore } from '../../stores/siteStore';
import toast from 'react-hot-toast';

export default function SettingsView() {
  const { logoUrl, siteName } = useSiteStore();

  const [settings, setSettings] = useState({
    appName: siteName || 'ConImpulso',
    appUrl: 'https://conimpulso.com',
    contactEmail: 'informacion@cristiangarcia.co',
    supportEmail: 'informacion@cristiangarcia.co',
    currency: 'COP',
    timezone: 'America/Bogota',
    maintenanceMode: false,
    advisorMonetization: false,
    userVerification: true,
    twoFactor: false,
    welcomeEmail: true,
    orderNotifications: true,
  });

  const set = (key, value) => setSettings((prev) => ({ ...prev, [key]: value }));

  const handleSave = () => {
    toast.success('Configuración guardada');
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Configuración</h1>
          <p className="text-gray-500">Configura los ajustes generales de la plataforma</p>
        </div>
        <button onClick={handleSave} className="btn-primary">Guardar cambios</button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left column */}
        <div className="lg:col-span-2 space-y-6">

          {/* Logo — redirige al Editor de Inicio */}
          <div className="card">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 bg-accent/20 rounded-xl flex items-center justify-center">
                <ImageIcon className="w-5 h-5 text-accent" />
              </div>
              <div>
                <h3 className="font-semibold text-gray-900">Logo de la plataforma</h3>
                <p className="text-sm text-gray-500">Se edita desde el Editor de Inicio</p>
              </div>
            </div>
            <div className="flex items-center gap-4">
              <div className="h-14 w-32 bg-primary rounded-xl flex items-center justify-center px-3">
                {logoUrl ? (
                  <img src={logoUrl} alt="Logo" className="max-h-10 max-w-[110px] object-contain" />
                ) : (
                  <div className="flex items-center gap-1.5">
                    <div className="w-7 h-7 bg-accent rounded-lg flex items-center justify-center">
                      <span className="text-primary font-bold text-sm">C</span>
                    </div>
                    <span className="text-white font-bold text-sm">ConImpulso</span>
                  </div>
                )}
              </div>
              <Link
                to="/admin/homepage-editor"
                className="flex items-center gap-2 px-4 py-2 bg-accent text-primary font-medium rounded-xl hover:bg-yellow-400 transition-colors text-sm"
              >
                Editar logo <ArrowRight className="w-4 h-4" />
              </Link>
            </div>
          </div>

          {/* General */}
          <div className="card">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-10 h-10 bg-blue-500/20 rounded-xl flex items-center justify-center">
                <SettingsIcon className="w-5 h-5 text-blue-600" />
              </div>
              <div>
                <h3 className="font-semibold text-gray-900">General</h3>
                <p className="text-sm text-gray-500">Nombre y URL de la plataforma</p>
              </div>
            </div>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Nombre de la plataforma</label>
                <input
                  type="text"
                  value={settings.appName}
                  onChange={(e) => set('appName', e.target.value)}
                  className="input-field w-full"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">URL de la aplicación</label>
                <input
                  type="text"
                  value={settings.appUrl}
                  onChange={(e) => set('appUrl', e.target.value)}
                  className="input-field w-full"
                />
              </div>
            </div>
          </div>

          {/* Email */}
          <div className="card">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-10 h-10 bg-green-500/20 rounded-xl flex items-center justify-center">
                <Mail className="w-5 h-5 text-green-600" />
              </div>
              <div>
                <h3 className="font-semibold text-gray-900">Email</h3>
                <p className="text-sm text-gray-500">Configuración de correos</p>
              </div>
            </div>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Email de contacto</label>
                <input
                  type="email"
                  value={settings.contactEmail}
                  onChange={(e) => set('contactEmail', e.target.value)}
                  className="input-field w-full"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Email de soporte</label>
                <input
                  type="email"
                  value={settings.supportEmail}
                  onChange={(e) => set('supportEmail', e.target.value)}
                  className="input-field w-full"
                />
              </div>
            </div>
          </div>

          {/* Localización */}
          <div className="card">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-10 h-10 bg-purple-500/20 rounded-xl flex items-center justify-center">
                <Globe className="w-5 h-5 text-purple-600" />
              </div>
              <div>
                <h3 className="font-semibold text-gray-900">Localización</h3>
                <p className="text-sm text-gray-500">Moneda y zona horaria</p>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Moneda</label>
                <select
                  value={settings.currency}
                  onChange={(e) => set('currency', e.target.value)}
                  className="input-field w-full"
                >
                  <option value="COP">Peso Colombiano (COP)</option>
                  <option value="USD">Dólar (USD)</option>
                  <option value="EUR">Euro (EUR)</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Zona horaria</label>
                <select
                  value={settings.timezone}
                  onChange={(e) => set('timezone', e.target.value)}
                  className="input-field w-full"
                >
                  <option value="America/Bogota">Bogotá (UTC-5)</option>
                  <option value="America/Mexico_City">Ciudad de México (UTC-6)</option>
                  <option value="America/Buenos_Aires">Buenos Aires (UTC-3)</option>
                </select>
              </div>
            </div>
          </div>

        </div>

        {/* Right column */}
        <div className="space-y-6">

          {/* Seguridad */}
          <div className="card">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 bg-purple-500/20 rounded-xl flex items-center justify-center">
                <Shield className="w-5 h-5 text-purple-600" />
              </div>
              <div>
                <h3 className="font-semibold text-gray-900">Seguridad</h3>
              </div>
            </div>
            <div className="space-y-4">
              <Toggle
                label="Verificación de usuarios"
                checked={settings.userVerification}
                onChange={(v) => set('userVerification', v)}
              />
              <Toggle
                label="Autenticación de dos factores"
                checked={settings.twoFactor}
                onChange={(v) => set('twoFactor', v)}
              />
            </div>
          </div>

          {/* Notificaciones */}
          <div className="card">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 bg-yellow-500/20 rounded-xl flex items-center justify-center">
                <Bell className="w-5 h-5 text-yellow-600" />
              </div>
              <div>
                <h3 className="font-semibold text-gray-900">Notificaciones</h3>
              </div>
            </div>
            <div className="space-y-4">
              <Toggle
                label="Email de bienvenida"
                checked={settings.welcomeEmail}
                onChange={(v) => set('welcomeEmail', v)}
              />
              <Toggle
                label="Notificaciones de pedidos"
                checked={settings.orderNotifications}
                onChange={(v) => set('orderNotifications', v)}
              />
            </div>
          </div>

          {/* Sistema */}
          <div className="card">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 bg-orange-500/20 rounded-xl flex items-center justify-center">
                <DollarSign className="w-5 h-5 text-orange-600" />
              </div>
              <div>
                <h3 className="font-semibold text-gray-900">Sistema</h3>
              </div>
            </div>
            <div className="space-y-4">
              <Toggle
                label="Modo mantenimiento"
                checked={settings.maintenanceMode}
                onChange={(v) => set('maintenanceMode', v)}
              />
              <p className="text-xs text-gray-400">Solo admins pueden acceder cuando está activo.</p>
              <div className="border-t border-gray-100 pt-4">
                <Toggle
                  label="Cobrar por conexión de asesores"
                  checked={settings.advisorMonetization}
                  onChange={(v) => set('advisorMonetization', v)}
                />
                <p className="text-xs text-gray-400 mt-1">Si está desactivado, los asesores conectan gratis.</p>
              </div>
            </div>
          </div>

          {/* Zona de peligro */}
          <div className="card border border-red-100 bg-red-50/50">
            <div className="flex items-center gap-3 mb-3">
              <AlertTriangle className="w-5 h-5 text-red-500" />
              <h3 className="font-semibold text-gray-900">Zona de peligro</h3>
            </div>
            <p className="text-xs text-gray-500 mb-4">Estas acciones son irreversibles. Procede con precaución.</p>
            <button className="w-full py-2 px-4 bg-red-600 hover:bg-red-700 text-white rounded-xl text-sm font-medium transition-colors">
              Reiniciar plataforma
            </button>
          </div>

        </div>
      </div>
    </div>
  );
}

function Toggle({ label, checked, onChange }) {
  return (
    <label className="flex items-center justify-between cursor-pointer">
      <span className="text-sm text-gray-700">{label}</span>
      <button
        type="button"
        onClick={() => onChange(!checked)}
        className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${checked ? 'bg-accent' : 'bg-gray-200'}`}
      >
        <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${checked ? 'translate-x-6' : 'translate-x-1'}`} />
      </button>
    </label>
  );
}
