// frontend-admin/src/views/UsersView.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Search, Plus, Filter } from 'lucide-vue-next'

const users = ref([
  { id: 1, name: 'Juan Pérez', email: 'juan@example.com', role: 'vendor', status: 'active', created: '2024-01-15' },
  { id: 2, name: 'María García', email: 'maria@example.com', role: 'client', status: 'active', created: '2024-02-20' },
  { id: 3, name: 'Carlos López', email: 'carlos@example.com', role: 'advisor', status: 'pending', created: '2024-03-10' },
  { id: 4, name: 'Ana Martínez', email: 'ana@example.com', role: 'vendor', status: 'suspended', created: '2024-01-05' },
])
</script>

<template>
  <div class="space-y-6">
    <div class="flex items-center justify-between">
      <div>
        <h1 class="text-2xl font-bold text-primary">Usuarios</h1>
        <p class="text-text-secondary">Gestionar usuarios de la plataforma</p>
      </div>
      <button class="btn-primary flex items-center gap-2">
        <Plus class="w-5 h-5" /> Nuevo usuario
      </button>
    </div>

    <div class="card">
      <div class="flex items-center gap-4 mb-6">
        <div class="relative flex-1 max-w-md">
          <Search class="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
          <input type="text" placeholder="Buscar usuarios..." class="input-field pl-10" />
        </div>
        <button class="btn-outline flex items-center gap-2">
          <Filter class="w-5 h-5" /> Filtros
        </button>
      </div>

      <div class="overflow-x-auto">
        <table class="w-full">
          <thead>
            <tr class="text-left text-sm text-text-secondary border-b border-gray-100">
              <th class="pb-3 font-medium">Usuario</th>
              <th class="pb-3 font-medium">Rol</th>
              <th class="pb-3 font-medium">Estado</th>
              <th class="pb-3 font-medium">Fecha registro</th>
              <th class="pb-3 font-medium">Acciones</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-50">
            <tr v-for="user in users" :key="user.id" class="text-sm">
              <td class="py-4">
                <div class="flex items-center gap-3">
                  <div class="w-10 h-10 bg-accent/20 rounded-full flex items-center justify-center">
                    <span class="text-primary font-bold">{{ user.name.charAt(0) }}</span>
                  </div>
                  <div>
                    <p class="font-medium text-primary">{{ user.name }}</p>
                    <p class="text-xs text-text-secondary">{{ user.email }}</p>
                  </div>
                </div>
              </td>
              <td class="py-4">
                <span class="px-2 py-1 bg-gray-100 rounded-full text-xs font-medium text-primary capitalize">
                  {{ user.role }}
                </span>
              </td>
              <td class="py-4">
                <span
                  :class="[
                    'px-2 py-1 rounded-full text-xs font-medium',
                    user.status === 'active' ? 'bg-green-100 text-green-700' :
                    user.status === 'pending' ? 'bg-yellow-100 text-yellow-700' :
                    'bg-red-100 text-red-700'
                  ]"
                >
                  {{ user.status }}
                </span>
              </td>
              <td class="py-4 text-text-secondary">{{ user.created }}</td>
              <td class="py-4">
                <button class="text-accent hover:text-accent-hover text-sm font-medium">Editar</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

// frontend-client/src/pages/admin/UsersView.jsx
import { useState, useEffect } from 'react';
import { Search, Plus, Pencil, Trash2, Eye, Filter } from 'lucide-react';
import api from '../../services/api';

export default function UsersView() {
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');

  useEffect(() => {
    loadUsers();
  }, []);

  const loadUsers = async () => {
    try {
      setLoading(true);
      // This would normally fetch from API
      // For now, set sample data
      setUsers([
        { id: 1, name: 'Super Admin', email: 'admin@nexuslab.com', roles: ['super_admin'], status: 'active' },
        { id: 2, name: 'Juan Pérez', email: 'juan@test.com', roles: ['vendor'], status: 'active' },
        { id: 3, name: 'María García', email: 'maria@test.com', roles: ['client'], status: 'active' },
        { id: 4, name: 'Carlos López', email: 'carlos@test.com', roles: ['advisor'], status: 'active' },
      ]);
    } catch (error) {
      console.error('Error loading users:', error);
    } finally {
      setLoading(false);
    }
  };

  const getRoleBadgeColor = (roles) => {
    if (roles.includes('super_admin')) return 'bg-red-100 text-red-700';
    if (roles.includes('vendor')) return 'bg-green-100 text-green-700';
    if (roles.includes('advisor')) return 'bg-blue-100 text-blue-700';
    return 'bg-gray-100 text-gray-700';
  };

  const getRoleLabel = (roles) => {
    if (roles.includes('super_admin')) return 'Super Admin';
    if (roles.includes('vendor')) return 'Vendedor';
    if (roles.includes('advisor')) return 'Asesor';
    if (roles.includes('client')) return 'Cliente';
    return 'Usuario';
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Usuarios</h1>
          <p className="text-gray-500">Gestiona los usuarios de la plataforma</p>
        </div>
        <button className="btn-primary flex items-center gap-2">
          <Plus className="w-5 h-5" />
          Nuevo Usuario
        </button>
      </div>

      {/* Filters */}
      <div className="flex items-center gap-4">
        <div className="relative flex-1 max-w-md">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
          <input
            type="text"
            placeholder="Buscar usuarios..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="input-field pl-10 w-full"
          />
        </div>
        <button className="btn-outline flex items-center gap-2">
          <Filter className="w-5 h-5" />
          Filtros
        </button>
      </div>

      {/* Users Table */}
      <div className="card">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="text-left text-sm text-gray-500 border-b border-gray-100">
                <th className="pb-3 font-medium">Nombre</th>
                <th className="pb-3 font-medium">Email</th>
                <th className="pb-3 font-medium">Rol</th>
                <th className="pb-3 font-medium">Estado</th>
                <th className="pb-3 font-medium">Acciones</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {users.map((user) => (
                <tr key={user.id} className="text-sm">
                  <td className="py-3 font-medium text-gray-900">{user.name}</td>
                  <td className="py-3 text-gray-500">{user.email}</td>
                  <td className="py-3">
                    <span className={`px-2 py-1 rounded-full text-xs font-medium ${getRoleBadgeColor(user.roles)}`}>
                      {getRoleLabel(user.roles)}
                    </span>
                  </td>
                  <td className="py-3">
                    <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                      user.status === 'active' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'
                    }`}>
                      {user.status}
                    </span>
                  </td>
                  <td className="py-3">
                    <div className="flex gap-2">
                      <button className="p-1.5 bg-gray-100 hover:bg-gray-200 rounded-lg" title="Ver">
                        <Eye className="w-4 h-4 text-gray-600" />
                      </button>
                      <button className="p-1.5 bg-blue-100 hover:bg-blue-200 rounded-lg" title="Editar">
                        <Pencil className="w-4 h-4 text-blue-600" />
                      </button>
                      <button className="p-1.5 bg-red-100 hover:bg-red-200 rounded-lg" title="Eliminar">
                        <Trash2 className="w-4 h-4 text-red-600" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
